/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BasicProject;

import org.junit.Test;

//import com.sun.tools.javac.util.Assert;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        basicFunctions UserData = new basicFunctions();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
       //System.out.println("Preparing to test");
        assertEquals("Pepito Perez", UserData.getUserName());
        //System.out.println("Test executed");
    }
}
