/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ValidateDataAccess;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library userData = new Library();
        //assertEquals("Pepito Perez", "Pepito Perez");
        assertEquals("Pepito Perez", userData.getName());
        assertEquals("*******", userData.getPassWord());
    }
}
