/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bootcamp.parent;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public void someImportantMethod() {

    }
}
