/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AccessUserPermission;
import BasicProject.basicFunctions;


public class Library {
    
	
	public static void main(String [] args) {
		
		//getFeatures(new basicFunctions()); 
		
	}
	
	
	
	public static void getFeatures(basicFunctions bf) {
		showUserName(bf.getUserName());
		showPassWord(bf.getPassword());
		
	}
	
	public static void Intro() {
		System.out.println("****** Welcome to Globant Access System ****************");
		System.out.println("Fullfill the records with your personal information below.");
	}
	public static void showUserName(String name) {
		System.out.println("Username : "+name);
	}
	public static void showPassWord(String password) {
		System.out.println("PassWord : "+password);
	}
	
	public static void askUserName() {
		System.out.println("Username : _ _ _ _ _ _ _");
	}
	public static void askPassWord() {
		System.out.println("PassWord : _ _ _ _ _ _ _ ");
	}
	
	public static basicFunctions getBasicFunctions() {
		return new basicFunctions();
	}
}
